# Start-Relux.ps1 - launch Relux locally from a SOURCE CHECKOUT (repo root).
#
# This is the developer/source launcher. It builds (or reuses) the relux-kernel
# binary from this checkout, points it at the committed dashboard bundle + the
# gitignored dev-data store, preflights the port, prints the dashboard URL, and
# runs the server in the foreground (Ctrl+C to stop).
#
# It is the source-checkout counterpart of the launcher baked into the packaged
# Windows release (the Start-Relux.ps1 generated by scripts\relux-package-local.ps1
# and shipped inside dist\relux-local-<version>-windows-x64\). The release script
# already has relux-kernel.exe next to it; THIS script builds it from source and
# resolves the in-repo dashboard-dist / dev-data paths instead. The port-preflight
# logic is adapted from that bundle launcher (and exercised by
# scripts\check-launcher-preflight.ps1).
#
# Usage (from the repo root):
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Port 20000
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Release
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -DryRun
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Doctor
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Help

[CmdletBinding()]
param(
    [int]$Port = 19891,
    # Build/use the optimized release binary instead of the faster-to-build debug one.
    [switch]$Release,
    # Validate prerequisites, port, and paths, print the plan, then exit WITHOUT
    # building or starting anything. Safe to run anytime.
    [switch]$DryRun,
    # Run `relux-kernel doctor` (health check) and exit with its status; no server.
    [switch]$Doctor,
    [switch]$Help
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot

function Show-Usage {
    Write-Host ""
    Write-Host "Start-Relux.ps1 - run Relux from this source checkout." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  -Port <n>   Loopback port for the dashboard/API (default 19891)."
    Write-Host "  -Release    Build/use target\release (optimized) instead of target\debug."
    Write-Host "  -DryRun     Check prereqs/port/paths and print the plan; build/start nothing."
    Write-Host "  -Doctor     Run the kernel health check and exit (no server)."
    Write-Host "  -Help       Show this help."
    Write-Host ""
    Write-Host "Examples:" -ForegroundColor DarkGray
    Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1"
    Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Port 20000"
    Write-Host ""
    Write-Host "Stop a running server with Ctrl+C (it runs in the foreground)." -ForegroundColor DarkGray
    Write-Host ""
}

if ($Help) { Show-Usage; exit 0 }

# -- repo-root guard -------------------------------------------------------
# The script lives at the repo root; $PSScriptRoot makes it runnable from any
# working directory. Confirm we are actually in a Relux checkout before doing
# anything so a misplaced copy fails loudly instead of half-building.
$KernelToml = Join-Path $Root "crates\relux-kernel\Cargo.toml"
if (-not (Test-Path -LiteralPath (Join-Path $Root "Cargo.toml")) -or -not (Test-Path -LiteralPath $KernelToml)) {
    Write-Host "ERROR: this does not look like a Relux source checkout." -ForegroundColor Red
    Write-Host ("Expected workspace Cargo.toml and {0} next to this script." -f $KernelToml) -ForegroundColor Red
    Write-Host "Run Start-Relux.ps1 from the root of the cloned repository." -ForegroundColor Yellow
    exit 1
}

# -- prerequisites ---------------------------------------------------------
$cargo = Get-Command cargo -ErrorAction SilentlyContinue
$haveCargo = [bool]$cargo

# -- binary resolution -----------------------------------------------------
$ReleaseExe = Join-Path $Root "target\release\relux-kernel.exe"
$DebugExe = Join-Path $Root "target\debug\relux-kernel.exe"
if ($Release) {
    $Exe = $ReleaseExe
    $Profile = "release"
    $BuildArgs = @("build", "-p", "relux-kernel", "--release")
} else {
    $Exe = $DebugExe
    $Profile = "debug"
    $BuildArgs = @("build", "-p", "relux-kernel")
}
$haveExe = Test-Path -LiteralPath $Exe
$needBuild = -not $haveExe

# -- dashboard bundle ------------------------------------------------------
$DashboardDist = Join-Path $Root "crates\relix-web-bridge\dashboard-dist"
$haveDashboard = Test-Path -LiteralPath (Join-Path $DashboardDist "index.html")

# -- data store (gitignored dev-data, resolved relative to the repo root) ---
$DataDb = Join-Path $Root "dev-data\relux\local.db"

# -- port preflight --------------------------------------------------------
# A second Relux (or any other process) already holding the loopback port is the
# most common first-run failure; the kernel would bind-fail AFTER a URL is
# printed. Probe 127.0.0.1:$Port up front and stop with an actionable message.
function Test-PortListening {
    param([int]$ProbePort)
    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $async = $client.BeginConnect("127.0.0.1", $ProbePort, $null, $null)
        if (-not $async.AsyncWaitHandle.WaitOne(400)) { return $false }
        try { $client.EndConnect($async) } catch { return $false }
        return $client.Connected
    } catch {
        return $false
    } finally {
        $client.Close()
    }
}

$portBusy = Test-PortListening -ProbePort $Port

# -- dry run: report the plan and exit, building/starting nothing -----------
if ($DryRun) {
    $alt = if ($Port -eq 20000) { 20001 } else { 20000 }
    Write-Host ""
    Write-Host "== Start-Relux dry run ==" -ForegroundColor Cyan
    Write-Host ("  repo root        : {0}" -f $Root)
    Write-Host ("  cargo present    : {0}" -f $(if ($haveCargo) { "yes ({0})" -f $cargo.Source } else { "NO - install Rust (https://rustup.rs)" })) -ForegroundColor $(if ($haveCargo) { "Green" } else { "Yellow" })
    Write-Host ("  build profile    : {0}" -f $Profile)
    Write-Host ("  binary           : {0}" -f $(if ($haveExe) { "{0} (reuse)" -f $Exe } else { "{0} (would build)" -f $Exe })) -ForegroundColor $(if ($haveExe) { "Green" } else { "Yellow" })
    Write-Host ("  dashboard bundle : {0}" -f $(if ($haveDashboard) { $DashboardDist } else { "MISSING - run `npm run build` in apps\dashboard" })) -ForegroundColor $(if ($haveDashboard) { "Green" } else { "Yellow" })
    Write-Host ("  data store       : {0}" -f $DataDb) -ForegroundColor DarkGray
    Write-Host ("  port {0,-5}       : {1}" -f $Port, $(if ($portBusy) { "IN USE - try -Port $alt" } else { "free" })) -ForegroundColor $(if ($portBusy) { "Yellow" } else { "Green" })
    Write-Host ("  dashboard URL    : http://127.0.0.1:{0}/dashboard" -f $Port) -ForegroundColor Green
    Write-Host ("  API URL          : http://127.0.0.1:{0}/v1/relux/state" -f $Port)
    Write-Host ""
    Write-Host "Dry run only - nothing was built or started." -ForegroundColor DarkGray
    Write-Host ""
    exit 0
}

# -- port guard (real run) -------------------------------------------------
if ($portBusy) {
    $alt = if ($Port -eq 20000) { 20001 } else { 20000 }
    Write-Host ""
    Write-Host ("ERROR: port {0} on 127.0.0.1 is already in use; Relux did not start." -f $Port) -ForegroundColor Red
    Write-Host "The most likely cause is that Relux is already running on this port." -ForegroundColor Yellow
    Write-Host ("  If so, open the running instance: http://127.0.0.1:{0}/dashboard" -f $Port) -ForegroundColor Cyan
    Write-Host "Otherwise another program holds that port. Start Relux on a free port, e.g.:" -ForegroundColor Yellow
    Write-Host ("  powershell -NoProfile -ExecutionPolicy Bypass -File .\Start-Relux.ps1 -Port {0}" -f $alt) -ForegroundColor Green
    Write-Host ""
    exit 1
}

# -- build the binary if needed --------------------------------------------
if ($needBuild) {
    if (-not $haveCargo) {
        Write-Host "ERROR: relux-kernel is not built yet and 'cargo' is not on PATH." -ForegroundColor Red
        Write-Host "Install the Rust toolchain (https://rustup.rs), reopen the shell, and re-run." -ForegroundColor Yellow
        exit 1
    }
    # Windows-local build-parallelism cap (see scripts\cargo-jobs.ps1): a cold,
    # fully parallel build of the heavy crates can exhaust the commit limit and
    # emit bogus link/ICE errors. Throttle peak parallelism for the cold build.
    $JobsArgs = @()
    $cargoJobs = Join-Path $Root "scripts\cargo-jobs.ps1"
    if (Test-Path -LiteralPath $cargoJobs) {
        . $cargoJobs
        $JobsArgs = Get-CargoJobsArgs
    }
    Write-Host ""
    Write-Host ("Building relux-kernel ({0}) from source - first build can take a few minutes ..." -f $Profile) -ForegroundColor Cyan
    Write-Host ("  cargo {0}" -f (($BuildArgs + $JobsArgs) -join " ")) -ForegroundColor DarkGray
    Push-Location $Root
    try {
        & cargo @BuildArgs @JobsArgs
    } finally {
        Pop-Location
    }
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $Exe)) {
        Write-Host "ERROR: build failed; see the cargo output above." -ForegroundColor Red
        exit 1
    }
}

# -- environment (resolved against the repo root) --------------------------
$env:RELUX_HTTP_ADDR = "127.0.0.1:$Port"
if ($haveDashboard) {
    $env:RELUX_DASHBOARD_DIST = $DashboardDist
} else {
    Write-Host "WARNING: dashboard bundle not found at crates\relix-web-bridge\dashboard-dist;" -ForegroundColor Yellow
    Write-Host "         the /dashboard route returns an honest 'not built' notice." -ForegroundColor Yellow
    Write-Host "         Build it with: cd apps\dashboard; npm install; npm run build" -ForegroundColor Yellow
}
New-Item -ItemType Directory -Path (Split-Path -Parent $DataDb) -Force | Out-Null

# -- doctor mode: health check and exit ------------------------------------
if ($Doctor) {
    Push-Location $Root
    try {
        & $Exe doctor
        $code = $LASTEXITCODE
    } finally {
        Pop-Location
    }
    exit $code
}

# -- serve (foreground; Ctrl+C to stop) ------------------------------------
Write-Host ""
Write-Host ("Starting Relux ({0} build) ..." -f $Profile) -ForegroundColor Cyan
Write-Host ("  Dashboard: http://127.0.0.1:{0}/dashboard" -f $Port) -ForegroundColor Green
Write-Host ("  API:       http://127.0.0.1:{0}/v1/relux/state" -f $Port)
Write-Host ("  Data:      {0}" -f $DataDb) -ForegroundColor DarkGray
Write-Host "  Press Ctrl+C to stop." -ForegroundColor DarkGray
Write-Host ""

Push-Location $Root
try {
    & $Exe serve
} finally {
    Pop-Location
}
